stages:
  - build
  - deploy

variables:
  IMAGE_NAME: mc-integration

cache:
  paths:
    - .m2/repository/

# ---------- BUILD ----------

build:
  stage: build
  tags:
    - mc-integration-deploy
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

# ---------- DEPLOY ----------

deploy:
  stage: deploy
  tags:
    - mc-integration-deploy
  dependencies:
    - build
  script:
    - ls -la target
    - docker build -t mc-integration:latest .
    - docker compose -f docker/docker-compose.prod.yml up -d --force-recreate
  only:
    - develop
    - feature/pipelineBugFix
