services:
  eureka:
    image: eureka-server
    ports:
    - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - mc-network

  redis:
    image: redis:8.6.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - mc-network

volumes:
  redis-data:

networks:
  mc-network:
    name: mc-network