version: '3.9'

services:
  mc-integration:
    image: mc-integration:latest
    container_name: mc-integration
    restart: unless-stopped
    ports:
      - "8765:8765"
    environment:
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_PASS: ${REDIS_PASS}
      EUREKA_HOST: http://eureka-server:8761/eureka
      SPRING_DATA_REDIS_HOST: redis
      JWT_PUBLIC_KEY_PATH: file:/app/keys/public.pem
    networks:
      - social-network
    volumes:
      - /opt/secrets/public.pem:/app/keys/public.pem:ro
      #- ./keys/public.pem:/app/keys/public.pem


networks:
  social-network:
    external: true